version: '3.8'

services:
  redis:
    image: redis:7.0
    container_name: redis-chatbot
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

volumes:
  redis-data:
