version: '3.3'

volumes:
  db-data:
  redis-data:

services:
  typebot-builder:
    image: samuellopes123/typebot:builder_prod
    restart: always
    ports:
      - '8080:3000'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file: .env
    depends_on:
      - redis

  typebot-viewer:
    image: samuellopes123/typebot:viewer_prod
    restart: always
    ports:
      - '8081:3000'
    env_file: .env
    depends_on:
      - redis

  redis:
    image: redis:7.0
    container_name: redis-chatbot
    restart: always
    ports:
      - '6390:6379'
    volumes:
      - redis-data:/data
  
  minio:
    image: minio/minio:RELEASE.2022-06-02T02-11-04Z
    container_name: minio-azure
    restart: always
    ports:
      - "9000:9000" # API S3
      - "9001:9001" # UI do MinIO
    env_file: .env
