version: '3.3'

volumes:
  db-data:

services:
  typebot-builder:
    image: samuellopes123/typebot:builder_prod
    restart: always
    ports:
      - '8080:3000'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file: .env

  typebot-viewer:
    image: samuellopes123/typebot:viewer_prod
    restart: always
    ports:
      - '8081:3000'
    env_file: .env

  minio:
    image: minio/minio
    container_name: minio-azure
    restart: always
    ports:
      - "9000:9000" 
      - "9001:9001" 
    env_file: .env  
    command: gateway azure
