version: '3.3'

volumes:
  db-data:
  redis-data:

services:
  typebot-builder:
    image: samuellopes123/typebot:builder
    restart: always
    ports:
      - '8080:3000'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file: .env
    depends_on:
      - redis

  typebot-viewer:
    image: samuellopes123/typebot:viewer
    restart: always
    ports:
      - '8081:3000'
    env_file: .env
    depends_on:
      - redis

  redis:
    image: redis:7.0
    container_name: redis-chatbot
    restart: always
    ports:
      - '6388:6379'
    volumes:
      - redis-data:/data
