name: Docker Image CI

on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latests
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Get the version
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_REF:14})
